### ISSUE TITLE
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

### ISSUE THREAD

**Issue by q9f** [status-im/nim-beacon-chain#4001] opened 2022-08-19 16:26 UTC
**Describe the bug**
Running a fresh install of a beacon node segfaults.

**To Reproduce**
1. Platform details (OS, architecture): Linux 5.19.1-arch2-1 SMP PREEMPT_DYNAMIC Thu, 11 Aug 2022 16:06:13 +0000 x86_64 GNU/Linux
2. Branch/commit used: tags/v22.7.0
3. Commands being executed: make ropsten or run-ropsten-beacon-node.sh
4. Relevant log lines:

```
~/.opt/status-im/nimbus-eth2 stable
❯ ./run-ropsten-beacon-node.sh     
Traceback (most recent call last, using override)
../sysdeps/x86_64/start.S(115) _start
/home/user/.opt/status-im/nimbus-eth2/vendor/nim-libp2p/libp2p/stream/bufferstream.nim(456) main
/home/user/.opt/status-im/nimbus-eth2/vendor/nim-libp2p/libp2p/stream/bufferstream.nim(446) NimMain
/home/user/.opt/status-im/nimbus-eth2/vendor/nim-libp2p/libp2p/stream/bufferstream.nim(437) PreMain
/home/user/.opt/status-im/nimbus-eth2/vendor/nim-libp2p/libp2p/stream/bufferstream.nim(147) PreMainInner
/home/user/.opt/status-im/nimbus-eth2/beacon_chain/sync/sync_protocol.nim(220) beacon_chain_sync_protocolInit000
/home/user/.opt/status-im/nimbus-eth2/beacon_chain/networking/eth2_network.nim(928) registerProtocol
/home/user/.opt/status-im/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system.nim(1266) insert
/home/user/.opt/status-im/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim(260) unsureAsgnRef
/home/user/.opt/status-im/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(610) signalHandler
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by tersec** [comment] 2022-10-27 13:29
Likely https://github.com/nim-lang/Nim/issues/20604

**Comment by tersec** [comment] 2022-10-27 13:32
What gcc version are are/were you using, if you remember?

**Comment by tersec** [comment] 2022-11-21 01:48
Root cause is https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107769#c1

**Comment by Eufix** [comment] 2023-01-18 12:30
I got a similar crash after initiating client shutdown.
Platform: Linux 5.15.0-56-generic #62-Ubuntu SMP  x86_64 GNU/Linux   
Client: statusim/nimbus-eth2:multiarch-v22.11.0     
   
```rocketpool_eth2  | NOT 2023-01-18 12:23:20.200+00:00 Shutting down after having received SIGINT topics="beacnde"
rocketpool_eth2  | NOT 2023-01-18 12:23:20.200+00:00 Graceful shutdown                          topics="beacnde"
rocketpool_eth2  | Traceback (most recent call last, using override)
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/stream/bufferstream.nim(482) main
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/stream/bufferstream.nim(475) NimMain
rocketpool_eth2  | /home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(2125) main
rocketpool_eth2  | /home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(1988) handleStartUpCmd
rocketpool_eth2  | /home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(1825) doRunBeaconNode
rocketpool_eth2  | /home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(1624) start
rocketpool_eth2  | /home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(1570) run
rocketpool_eth2  | /home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(1494) stop
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncloop.nim(1203) waitFor
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncloop.nim(295) poll
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(369) futureContinue
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/multistream.nim(183) handle
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/stream/lpstream.nim(312) close
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/stream/lpstream.nim(312) close
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system.nim(230) close
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim(440) newObj
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim(411) rawNewObj
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim(789) collectCT
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim(797) collectCT
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim(770) collectCTBody
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim(727) collectZCT
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/gc_common.nim(413) prepareDealloc
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(610) signalHandler
rocketpool_eth2  | SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by tersec** [comment] 2023-01-18 15:08
@Eufix this is likely a separate issue, and you're welcome to file it as such should you be so inclined.

This particular issue isn't all `SIGSEGV`s, but that particular one with that particular/specific signature.

**Comment by chfast** [comment] 2023-01-31 09:08
Happens to me on shutdown too. I use GCC 11 or 12.

**Comment by tersec** [comment] 2023-01-31 14:08
Opened https://github.com/status-im/nimbus-eth2/issues/4571 to track the very specific segfault this issue was meant to track

(but regardless, not all segfaults are the same, and segfault-on-
```
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncloop.nim(1203) waitFor
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncloop.nim(295) poll
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(369) futureContinue
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/multistream.nim(183) handle
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/stream/lpstream.nim(312) close
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/stream/lpstream.nim(312) close
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system.nim(230) close
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim(440) newObj
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim(411) rawNewObj
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim(789) collectCT
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim(797) collectCT
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim(770) collectCTBody
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim(727) collectZCT
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/gc_common.nim(413) prepareDealloc
rocketpool_eth2  | /home/user/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(610) signalHandler
```
can/should be opened as its own issue

**Comment by zah** [comment] 2023-03-11 07:57
I'm closing this as duplicate of #4571.

**Closed as completed by zah** 2023-03-11 07:57 UTC
