### ISSUE TITLE
make eth2_network_simulation fails with tmux

### ISSUE THREAD

**Issue by tersec** [status-im/nim-beacon-chain#1353] opened 2020-07-21 17:04 UTC
```
$ make eth2_network_simulation
can't find window: start-script
make: *** [Makefile:158: eth2_network_simulation] Error 1
$ tmux -V
tmux 3.1b
```

**Comment by arnetheduck** [comment] 2020-07-22 06:58
this happens to me as well, since the tmux changes

**Comment by zah** [comment] 2020-07-22 07:14
I haven't been able to reproduce this. I'll try it on a few servers and VMs with more more pristine environments to see if I'll strike any luck. I suspect that the reason it's happening is that some of the commands launched in the `start-script` window fails and this leads to the early closing of that window. You can perhaps try to debug this just by inserting echo statements between the commands to see what's being executed.

**Closed** 2020-07-23 16:01 UTC
