### ISSUE TITLE
Crash after not being able to construct EpochRef

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#4128] opened 2022-09-16 08:36 UTC
https://discord.com/channels/613988663034118151/771033358363918347/1020220675706859541

From a RocketPool user

![image](https://user-images.githubusercontent.com/22738317/190594991-45b09d76-4b30-4e0f-88a5-e1f0abaee014.png)

**Comment by zah** [comment] 2022-09-21 11:10
Duplicate of https://github.com/status-im/nimbus-eth2/issues/4063

**Closed as completed by zah** 2022-09-21 11:10 UTC
