### ISSUE TITLE
first validator has suspicious balance after running state sim

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#150] opened 2019-03-04 20:28 UTC
in state sim, with `--attesterRatio=1 --slots=4096` everyone should be attesting - however, the first validator is getting penalized - investigate this:

https://twitter.com/jcksie/status/1101580136208629760

[state.tar.gz](https://github.com/status-im/nim-beacon-chain/files/2928073/state.tar.gz)

**Comment by tersec** [comment] 2019-03-05 20:34
It's not just the first validator.

There are five missing attesters at epoch processing time. The first attester (because `state_sim.nim` doesn't attest on first slot) and the last four of the epoch:
> {1, 54, 22, 25, 27}

Where the overall validator sequence by shard is:
> [25, 15, 30, 50, 20, 4, 35, 47, 49, 40, 32, 63, 31, 23, 60, 53, 3, 59, 21, 7, 33, 52, 48, 38, 36, 13, 2, 24, 39, 14, 6, 8, 34, 10, 5, 9, 19, 44, 17, 57, 62, 42, 26, 29, 37, 58, 28, 12, 41, 46, 45, 16, 43, 0, 56, 11, 61, 18, 55, 51, 22, 1, 54, 27]

This is related to the inclusion delay. So that's the direct cause, at least.

**Comment by arnetheduck** [comment] 2019-03-05 20:35
ah right how silly.. `start.sh` doesn't attach all validators

**Comment by tersec** [comment] 2019-06-13 05:57
Resolved by updating to a spec which doesn't use `epoch_boundary_root`, as far as I've been able to (not) reproduce.

**Closed by tersec** 2019-06-13 05:57 UTC
