### ISSUE TITLE
Build Fails on v22.7.0

### ISSUE THREAD

**Issue by joesixpack** [status-im/nim-beacon-chain#3992] opened 2022-08-18 17:59 UTC
```
exec /home/user/entry_point.sh: permission denied
make: *** [Makefile:694: dist-amd64] Error 1
```

**Comment by arnetheduck** [comment] 2022-09-08 12:34
This looks like a docket setup issue - can you post some more information about how exactly you're trying to build?

**Comment by joesixpack** [comment] 2022-09-23 23:55
Followed the official guide.

**Comment by arnetheduck** [comment] 2022-10-27 14:12
Can you proved a bit more information? Which guide? what commands did you run? what version were you using?

**Comment by arnetheduck** [comment] 2023-01-05 21:38
closing for now since we're unable to reproduce without further information - do reopen if you find time to try  this again.

**Closed as completed by arnetheduck** 2023-01-05 21:38 UTC
