### ISSUE TITLE
nimbus-validator `pollForValidatorIndices` uses inappropriate limits for batching

### ISSUE THREAD

**Issue by jshufro** [status-im/nim-beacon-chain#5042] opened 2023-06-08 21:38 UTC
**Describe the bug**
A validator with many keys will query `/eth/v1/beacon/states/head/validators` in batches of up to 1024 keys at a time, referencing `ClientMaximumValidatorIds`. These query sizes aren't tunable with config flags, and can be too long for some http transports.

Here's the relevant blurb about `ClientMaximumValidatorIds` from `rest_types.nim`:

```nim
  # Maximum number of validators that can be sent in single request by
  # validator client (VC).
  # NOTE: This value depend on beacon node's `rest-max-headers-size`
  # configuration option.
  #
  # Size of public key in HTTP request could be calculated by formula -
  # bytes48 * 2 + len("0x") + len(",") = 99 bytes.
  # So 1024 keys will occupy 101,376 bytes. Default value for HTTP headers size
  # is 128Kb = 131,072 bytes.
  ClientMaximumValidatorIds* = 1024
```

Note that `/eth/v1/beacon/states/head/validators` doesn't pass the public keys in headers, as the comment above suggests, but instead adds them to the query string (eg `/eth/v1/beacon/states/head/validators?id=0x...,0x....,0x....`).

Query strings are passed in the http [Request-Line](https://www.rfc-editor.org/rfc/rfc2616#section-5.1), not the headers, so the above comments on limiting size to 128Kb for header size limits isn't pertinent to this endpoint.

Additionally, the code (`pollForValidatorIndices`), doesn't seem to respect `rest-max-headers-size`- it uses `min(ClientMaximumValidatorIds, len(validatorIdents))` which implies this behavior isn't configurable.

We have our beacon nodes behind a somewhat strict proxy- 32 Kb is our maximum URL length. Today, a user with many validators managed to hit that limit and experienced downtime until we made special accommodations for him.

There's a few ways to fix this-
1) Smaller batches by default so as to not exceed a lower limit, like 16 Kb (so around 150 pub keys per batch- still pretty high, considering the context)
2) Config flag making batch size dynamic
3) Both of the above
4) Use some other endpoint to map pubkey->indices without having to specify the pubkeys in the URL's query string.

**To Reproduce**

- Create a few hundred validators on a nimbus vc, pointed at a nimbus bn behind cloudflare
or
- Curl any webserver behind cloudflare with a URL in excess of 32 Kb length
or
- I can provide a curl privately, though it will be 32 Kb+ so it won't fit in a discord DM, say.

1. Platform details (OS, architecture): any
2. Branch/commit used: main/master
3. Commands being executed: nimbus_validator_client
4. Relevant log lines: 
```
Beacon node provides unexpected response    node=[redacted]
Unable to get head state's validator information reason="Beacon node reports unexpected status" service=duties_service
```
In our case, the 'unexpected status' is a HTTP 414 from Cloudflare:
```html
<html>
<head><title>414 Request-URI Too Large</title></head>
<body>
<center><h1>414 Request-URI Too Large</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```

**Screenshots**

**Additional context**

**Comment by arnetheduck** [comment] 2023-06-14 06:15
duplicate of #4980

**Closed as not planned by arnetheduck** 2023-06-14 06:15 UTC
