### ISSUE TITLE
Extremely long compile-times

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#2293] opened 2021-02-04 13:30 UTC
The compilation times are getting out-of-hand. Even on my top end machine we have

`datatypes.nim` taking 4.5 seconds
`clearance.nim` taking 44 seconds

![image](https://user-images.githubusercontent.com/22738317/106899005-2644dd00-66f5-11eb-8160-b94b187e4c45.png)
![image](https://user-images.githubusercontent.com/22738317/106899050-3066db80-66f5-11eb-99f8-0829fea20570.png)

This means that on a Raspberry Pi which has a much lower clock, compiling just clearance.nim would take minutes.

This negatively impacts the test suite, we won't be able to test hard forks in the future in the CI time alloted.
It also impacts user experience who need to build via docker or custom compile on their machine.

It also wastes our own dev time.

**Comment by mratsim** [comment] 2021-02-04 13:37
block_pool_types is at 45s
beacon_chain_db at 30s
![image](https://user-images.githubusercontent.com/22738317/106900196-85572180-66f6-11eb-9c47-9092f22aaeb1.png)

**Comment by mratsim** [comment] 2021-02-04 13:41
SQLite 3 is likely the main culprit
![image](https://user-images.githubusercontent.com/22738317/106900609-00203c80-66f7-11eb-9de5-404833187da3.png)

And I assume BearSSL and secp256k1 that we build statically as well

**Comment by zah** [comment] 2021-02-04 18:27
Can you also post some build times with `-d:disableLTO` for comparison?

**Comment by arnetheduck** [comment] 2021-02-16 15:00
these build times I assume are with a cold `nimcache`? ie for dev time, the practical impact is much less because libraries like secp and sqlite are not recompiled generally. also, optimization does indeed take time - we build with full optimization all the time which increases the time of the build but benefits the overall runtime of the test suite

**Comment by mratsim** [comment] 2021-02-16 15:55
No the nimcache is hot.

**Comment by arnetheduck** [comment] 2021-02-16 17:18
Probaby something is up with your nimcache then:

```
[arnetheduck@tempus nim-beacon-chain]$ time ./env.sh nim --hints:off c -d:release vendor/nim-eth/eth/db/kvstore_sqlite3.nim 

real	0m42,176s
user	0m41,335s
sys	0m0,667s
[arnetheduck@tempus nim-beacon-chain]$ time ./env.sh nim --hints:off c -d:release vendor/nim-eth/eth/db/kvstore_sqlite3.nim 

real	0m9,111s
user	0m8,812s
sys	0m0,297s
```

keep in mind that every time you compile a new project (pass a new nim file), there's a new `nimcache` created.

**Comment by stefantalpalaru** [comment] 2021-02-18 01:35
Maybe you have ccache enabled. I get 1m4.418s and 1m3.002s, respectively.

**Comment by arnetheduck** [comment] 2021-02-18 06:40
and if you try a third time? ie nimcache is a bit wonky at times

**Comment by stefantalpalaru** [comment] 2021-02-18 07:13
You're right. The third run is 0m17.284s :-)

Something's off with Nim's cache invalidation, then.

**Comment by arnetheduck** [comment] 2021-02-18 07:25
see if we can report a repro to upstream

**Comment by jclapis** [comment] 2021-03-17 21:44
> This means that on a Raspberry Pi which has a much lower clock, compiling just clearance.nim would take minutes.

For what it's worth, I can confirm that it takes around 17 minutes to build v1.0.10 on my Pi (2 GHz). Luckily I don't do a whole lot of tweaking...

**Comment by arnetheduck** [comment] 2023-09-25 14:34
While annoying, this is not directly fixable in nimbus beyond what's been done already, ie ensure maximum parallelism of build etc - closing for now, more concrete build problems can be opened as separate issues should they be discovered (ie avoidable compilation time)

**Closed as completed by arnetheduck** 2023-09-25 14:34 UTC
Labels: :checkered_flag: performance, test suite, polish, User experience
