### ISSUE TITLE
"No working beacon nodes available" logs on validator client

### ISSUE THREAD

**Issue by canbal99** [status-im/nim-beacon-chain#3037] opened 2021-10-28 09:16 UTC
**Describe the bug**
I am running 2 validators on prater network (on rpi4 8GB booting with 1TB USB SSD).
My Beaconchain and Validator processes are separate.
Even if there is no problem with my BC client, I continuously see this error on validator client.
"No working beacon nodes available"
NOTE: Validator is attesting properly during that time. No problem with performing tasks.

I also have a script which runs periodically (every 15 or every 30 minutes) to check health of my processes.
Following eth api requests are executed using curl command:
- node/version
- node/peer_count
- node/syncing
- debug/beacon/heads (replaced with beacon/headers/head)

**To Reproduce**
It always happens in my setup.
Might be related with api requests and/or running a separate validator.

**Additional context**
client version(local-build): Nimbus/v1.5.2-3b3d8b-stateofus
[bc.vc.debug.logs.zip](https://github.com/status-im/nimbus-eth2/files/7432842/bc.vc.debug.logs.zip)

**Comment by arnetheduck** [comment] 2022-06-27 19:56
Hi - since this report, we've addressed a large number issues in the VC-BN communicaiton protocol - I would expect this has been fixed as I'm unable to reproduce - do give v22.6.0 a whirl.

**Comment by arnetheduck** [comment] 2022-09-21 14:31
Closing as VC-BN connectivity has thoroughly been reviewed since.

**Closed as completed by arnetheduck** 2022-09-21 14:31 UTC
Labels: VC
