### ISSUE TITLE
Add documentation for CLI option --web3-mode

### ISSUE THREAD

**Issue by jt9897253** [status-im/nim-beacon-chain#2940] opened 2021-10-01 14:07 UTC
**Is your feature request related to a problem? Please describe.**

I was not able to test the connection to the web3 provider. Problem was that no validator was attached and the `web3-mode` default configuration is `auto` and only connects to the web3 provider, if a validator is attached.
To find the problem, I had to look at the source code until I learned about the undocumented `web3-mode` command line option. When I change it from the default value `auto` to `enabled`, nimbus finally made connections to the Eth1 client.

**Describe the solution you'd like**

Add documentation for the `--web3-mode` command line option.

Updating the documentation at https://nimbus.guide/eth1.html would probably also be a good idea.

**Comment by arnetheduck** [comment] 2021-10-12 10:57
Duplicate of https://github.com/status-im/nimbus-eth2/issues/2685

**Closed as completed by arnetheduck** 2021-10-12 10:57 UTC
